//! Language-model types and the [`LanguageModel`] trait.

use std::sync::Arc;

use async_trait::async_trait;
use pipecrab_runtime::MaybeSendSync;

/// A role in the language model's chat context.
///
/// Unlike [`pipecrab_core::Role`], this includes [`ChatRole::System`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ChatRole {
    /// The system prompt.
    System,
    /// A turn from the user.
    User,
    /// A turn generated by the model.
    Assistant,
}

/// One turn in a [`Conversation`]: a [`ChatRole`] and its text.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Message {
    /// Who produced this turn.
    pub role: ChatRole,
    /// The turn's text.
    pub content: Arc<str>,
}

impl Message {
    /// Creates a system message.
    pub fn system(content: impl Into<Arc<str>>) -> Self {
        Self {
            role: ChatRole::System,
            content: content.into(),
        }
    }

    /// Creates a user message.
    pub fn user(content: impl Into<Arc<str>>) -> Self {
        Self {
            role: ChatRole::User,
            content: content.into(),
        }
    }

    /// Creates an assistant message.
    pub fn assistant(content: impl Into<Arc<str>>) -> Self {
        Self {
            role: ChatRole::Assistant,
            content: content.into(),
        }
    }
}

/// Messages passed to [`LanguageModel::generate`], oldest first.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Conversation {
    /// The turns so far, in order.
    pub messages: Vec<Message>,
}

/// Optional parameters for one [`LanguageModel::generate`] call.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct GenParams {
    /// Upper bound on generated tokens, if any.
    pub max_tokens: Option<u32>,
    /// Sampling temperature, if any.
    pub temperature: Option<f32>,
    /// An engine-specific grammar or schema constraint.
    pub grammar: Option<Arc<str>>,
}

/// One incremental piece of a generation: a text delta to append.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TokenOut {
    /// The text to append to the reply so far.
    pub delta: Arc<str>,
}

/// A stream of generated text deltas.
#[cfg(not(target_arch = "wasm32"))]
pub type TokenStream = futures::stream::BoxStream<'static, Result<TokenOut, LmError>>;
/// A stream of generated text deltas.
#[cfg(target_arch = "wasm32")]
pub type TokenStream = futures::stream::LocalBoxStream<'static, Result<TokenOut, LmError>>;

/// Generates text incrementally from a chat context.
///
/// Implementations should be handles to workers that own mutable model state;
/// trait methods use `&self` so stage effects remain safe to cancel.
///
/// # Streaming is a barge-in requirement
///
/// Each [`TokenStream`] item is a preemption point. Dropping the stream stops
/// consumption; [`LanguageModel::cancel`] stops engine production.
///
/// [`LanguageModel::cancel`] is a [`pipecrab_core::Processor`] control call.
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
pub trait LanguageModel: MaybeSendSync {
    /// Generate a reply to `convo` under `params`, yielding text deltas.
    ///
    /// The returned stream must be safe to drop between items.
    async fn generate(
        &self,
        convo: &Conversation,
        params: &GenParams,
    ) -> Result<TokenStream, LmError>;

    /// Aborts in-flight generation synchronously and idempotently.
    fn cancel(&self);

    /// Serializes the worker's session state.
    async fn save_state(&self) -> Result<Vec<u8>, LmError>;

    /// Restore worker session state previously produced by
    /// [`save_state`](Self::save_state).
    async fn load_state(&self, blob: &[u8]) -> Result<(), LmError>;
}

/// An error from a [`LanguageModel`] call.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LmError {
    /// A generation engine failure.
    Engine(String),
}

impl std::fmt::Display for LmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LmError::Engine(msg) => write!(f, "lm engine error: {msg}"),
        }
    }
}

impl std::error::Error for LmError {}
